{% set name = "nvitop" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d298d878a18a1b8da4116fd97d53b10a0bf0f8635d7a62769134b8a4d5585c9

build:
  # TODO: enable Windows support when package `windows-curses` is available
  skip: true  # [win]
  entry_points:
    - nvitop = nvitop.cli:main
    - nvisel = nvitop.select:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - cachetools >=1.0.1
    - colorama >=0.4.0  # [win]
    - nvidia-ml-py >=11.450.51,<11.516.0a0
    - psutil >=5.6.6
    - python
    - termcolor >=1.0.0
    - windows-curses >=2.2.0  # [win]

test:
  imports:
    - nvitop
  commands:
    - pip check
    - nvitop --help
    - nvisel --help
  requires:
    - pip

about:
  home: https://github.com/XuehaiPan/nvitop
  summary: An interactive NVIDIA-GPU process viewer, the one-stop solution for GPU process management.
  dev_url: https://github.com/XuehaiPan/nvitop
  doc_url: https://nvitop.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSE
    - COPYING

extra:
  recipe-maintainers:
    - XuehaiPan
