{% set name = "nvitop" %}
{% set version = "1.4.0" %}
{% set build_number = 1 %}
{% set sha256 = "92f313e9bd89fe1a9d54054e92f490f34331f1b7847a89ddaffd6a7fde1437bb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # TODO: enable Windows support when package `windows-curses` is available
  skip: true  # [win]
  entry_points:
    - nvitop = nvitop.cli:main
    - nvisel = nvitop.select:main
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ build_number }}

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - pip
    - setuptools
    - python
  run:
    - cachetools >=1.0.1
    - colorama >=0.4.0  # [win]
    - nvidia-ml-py >=11.450.51,<12.561.0a0
    - psutil >=5.6.6
    - python
    - termcolor >=1.0.0
    - windows-curses >=2.2.0  # [win]

test:
  imports:
    - nvitop
  commands:
    - pip check
    - nvitop --help
    - nvisel --help
  requires:
    - pip

about:
  home: https://github.com/XuehaiPan/nvitop
  summary: An interactive NVIDIA-GPU process viewer, the one-stop solution for GPU process management.
  dev_url: https://github.com/XuehaiPan/nvitop
  doc_url: https://nvitop.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSE
    - COPYING

extra:
  recipe-maintainers:
    - XuehaiPan
