{% set name = "nvitop" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6bee68ca03dc447b3372bcdad84e30fc376ae9c8113e32108567ee8d7d2743ea

build:
  # TODO: enable Windows support when package `windows-curses` is available
  skip: true  # [win]
  entry_points:
    - nvitop = nvitop.cli:main
    - nvisel = nvitop.select:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python
  run:
    - cachetools >=1.0.1
    - colorama >=0.4.0  # [win]
    - nvidia-ml-py >=11.450.51,<11.516.0a0
    - psutil >=5.6.6
    - python
    - termcolor >=1.0.0
    - windows-curses >=2.2.0  # [win]

test:
  imports:
    - nvitop
  commands:
    - pip check
    - nvitop --help
    - nvisel --help
  requires:
    - pip

about:
  home: https://github.com/XuehaiPan/nvitop
  summary: An interactive NVIDIA-GPU process viewer, the one-stop solution for GPU process management.
  dev_url: https://github.com/XuehaiPan/nvitop
  doc_url: https://nvitop.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - XuehaiPan
