{% set name = "nvitop" %}
{% set version = "1.5.0" %}
{% set build_number = 0 %}
{% set sha256 = "ff7549c4cf8d2af7442ac00042fed19a26326525742fe503eec3bcc9dbe8ca4b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  entry_points:
    - nvitop = nvitop.cli:main
    - nvisel = nvitop.select:main
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ build_number }}

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - __unix  # [unix]
    - __win   # [win]

    - nvidia-ml-py >=11.450.51,<12.571.0a0
    - psutil >=5.6.6

    - colorama >=0.4.0        # [win]
    - windows-curses >=2.2.0  # [win]

test:
  imports:
    - nvitop
  commands:
    - pip check
    - nvitop --help
    - nvisel --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/XuehaiPan/nvitop
  summary: An interactive NVIDIA-GPU process viewer, the one-stop solution for GPU process management.
  dev_url: https://github.com/XuehaiPan/nvitop
  doc_url: https://nvitop.readthedocs.io
  license: GPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSE
    - COPYING

extra:
  recipe-maintainers:
    - XuehaiPan
